---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/sinensia/hello-2048/public_html/
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: '0644'
        directory_mode: '0755'
